version: "3"
services:
  go-rustdesk-server:
    image: danbai225/go-rustdesk-server:latest
    container_name: go-rustdesk-server
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./logs/:/app/logs
      - ./clover-db/:/app/clover-db
      - ./key/:/app/key
    ports:
      - "21114:21114"
      - "21115:21115"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21117:21117"
      - "21120:21120/udp"