// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type Info struct {
	// 用户id
	UUID string `json:"uuid"`
	// 用户名
	Username string `json:"username"`
	// 是否是管理员
	IsAdmin bool `json:"isAdmin"`
	// token
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}
